#!/bin/sh
# If using normal root, avoid changing anything.
if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
        exit 0
fi

MASTER_ERROR_CODE=0
for f in `find $RPM_BUILD_ROOT -type f -name "*.la" ` ; do
   ERROR_CODE=0
   grep -q  "libdir=.*$RPM_BUILD_ROOT" $f && ERROR_CODE=1
   grep -q "libdir=.*/usr/src/packages/BUILD/" $f && ERROR_CODE=2
   grep -q "dependency_libs=.*$RPM_BUILD_ROOT" $f && ERROR_CODE=3
   grep -q "dependency_libs=.*/usr/src/packages/BUILD/" $f && ERROR_CODE=4
   chmod -x -- "$f" 2>/dev/null
   if [ "$ERROR_CODE" != "0" ] ; then
       MASTER_ERROR_CODE=$ERROR_CODE
       echo "found trace of \$RPM_BUILD_ROOT or \$RPM_BUILD_DIR"
       echo "in installed .la file $f"
   fi

   . $f
   NON_TRIVIAL_DEP=0
   if test -z "$dependency_libs" -a "$shouldnotlink" = "no"; then
       echo "WARNING: found empty dependency_libs variable. please remove"
       echo "       the pointless libtool .la file $f"
       echo "         If you don't understand this, mailto=rguenther@suse.de"
       # make this an error after 10.2
       #MASTER_ERROR_CODE=$ERROR_CODE
       NON_TRIVIAL_DEP=1
   fi

   for dep in $dependency_libs; do
       case $dep in
           -l*)
               NON_TRIVIAL_DEP=1
               break
               ;;
           *.la)
               NON_TRIVIAL_DEP=1
               break
               ;;
           -L/usr/lib)
               ;;
           -L/lib)
               ;;
           -L/usr/lib64)
               ;;
           -L/lib64)
               break
               ;;
           -L*)
               NON_TRIVIAL_DEP=1
               break
	       ;;
           *)
             ;;
       esac
   done

   if test "$shouldnotlink" != "yes" -a $NON_TRIVIAL_DEP = 0; then
       echo "WARNING: found only trivial dependencies. consider removing"
       echo "         the pointless libtool .la file $f"
       echo "         If you don't understand this, mailto=rguenther@suse.de"
   fi
done

exit $MASTER_ERROR_CODE
