#!/bin/bash

if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
       exit 0
fi

if [ -n "$BRP_FIPSHMAC_FILES" ] ; then
	# this is the fipscheck version
	FIPSHMAC=$(type -p fipshmac)
	if [ -z "$FIPSHMAC" ] ; then
		# this is the libkcapi-tools version (more modern)
		FIPSHMAC=/usr/libexec/libkcapi/fipshmac
	fi
	if [ -x "$FIPSHMAC" ] ; then
		RES=0
		for item in $BRP_FIPSHMAC_FILES ; do
			$FIPSHMAC $item || RES=1
		done
		if [ "$RES" != "0" ] ; then
			echo "brp-50-generate-fips-hmac (using $FIPSHMAC) failed"
			exit 1
		fi
	else
		echo "fipshmac ($FIPSHMAC) is not executable"
		exit 1
	fi
fi

