#!/bin/sh
set -e
NAME=brp-check-suse
VERSION=13.2
scmver=`git log -n1 --date=short --pretty=format:"git%cd.%h"|sed 's@-@@g'`
fullver="$VERSION${scmver:++}$scmver"
pfx="$NAME${fullver:+-$fullver}"
fn="$pfx".tar.xz
git archive --prefix="$pfx"/ HEAD | xz > $fn
echo "version $fullver -> $fn"
